### ISSUE TITLE
`Check if an array contains a given value` is just an alias

### ISSUE THREAD

**Issue by abhijeetkpawar** [phuocng/1loc#182]
Solution of `Check if an array contains a given value` is just the call to native `includes()` method.
I think this should not be termed as 1-liner code, otherwise every native method would satisfy for this list.
https://github.com/phuoc-ng/1loc/blob/master/collections/array/check-if-an-array-contains-a-given-value.md

**Comment by phuocng** [comment]
@abhijeetkpawar 
That is the principle I try to follow. If the snippet is supported by the native API directly, we absolutely don't need it.
In that case, I'll remove the snippet you mentioned.
