### ISSUE TITLE
Checking for an empty array can be faster 

### ISSUE THREAD

**Issue by inoyakaigor** [phuocng/1loc#263]
I made a simple performance test and it shows that getting length of array keys is not optimal code. I propose change it to `a.filter(Boolean).length > 0`. This code can be faster from 4.5 (Firefox) or 5.9 (Chrome) to 26 (Safari) times.

![image](https://user-images.githubusercontent.com/1235286/82888159-ab1a0d00-9f51-11ea-88ff-15259a6b55ea.png)

**Comment by robinpokorny** [comment]
Hey Igor, that is a really good insight.

However, as you probably know, this is not universal. There could be valid falsy values in the array, like `['', 0]`. Which this would mark as empty.

However, seeing how fast `a.lenght` is, maybe it makes sense to add this before the keys check, WDYT?

**Comment by inoyakaigor** [comment]
Yeah, exactly, falsy. How I could forget!
I think there is still need filter function and therefore I suppose better solution wich cover edge cases is
```javascript
Array.isArray(a) && a.length > 0 && a.filter(el => el === undefined)
```
Also checking can be faster if use latest ES2020 feature ([link](https://jsperf.com/fastest-check-of-array-length/)):
![image](https://user-images.githubusercontent.com/1235286/85126890-0c728a80-b237-11ea-9605-77eddbac8ebe.png)

For history: my jsperf test from initial message https://jsperf.com/object-keys-vs-array-length

**Comment by phuocng** [comment]
Can you make a PR?

**Comment by inoyakaigor** [comment]
Yes of course

**Comment by inoyakaigor** [comment]
@phuoc-ng Done #302
