### ISSUE TITLE
Assigning to a new array literal does not empty an array

### ISSUE THREAD

**Issue by marlowpayne** [phuocng/1loc#72]
`const empty = arr => arr = [];`

This code snippet will not empty the `arr` argument, as shown below:

![Screen Shot 2020-04-24 at 8 25 51 AM](https://user-images.githubusercontent.com/1747353/80233750-d684a180-860b-11ea-9ffb-15d9984b872b.png)

**Comment by phuocng** [comment]
It was my mistake while trying to push many snippets :)
It's fixed now.
