### ISSUE TITLE
Create an array of numbers in the given range

### ISSUE THREAD

**Issue by ksrakhilesh** [phuocng/1loc#98]
Should Be 
`const range1 = (min, max) => Array(max - min + 1).fill(0).map((_, i) => min + i);`

**Comment by phuocng** [comment]
@ksrakhilesh Yes, both returns the same result. Actually, I used the same approach [initially](https://github.com/phuoc-ng/1loc/commit/d3ea79dd2dcac016d2a9dd4ea295ae3915516103#diff-ec840e19684cae25b7c688399e556f43).

Anyway, I updated the post using both ways.

**Comment by martinschilliger** [comment]
Just curious: Is there a benefit on either approach?

**Comment by phuocng** [comment]
@martinschilliger No, it's the same. It's just another way to describe.
